src/bn/relic_bn_gcd.c, src/fp/relic_fp_param.c
The variable is set but not used.
=> remove unused variables

src/cp/relic_cp_bgn.c, test/test_cp.c
The BGN decryption funcitons  cp_bgn_dec1, cp_bgn_dec2 and cp_bgn_dec didn't handle the case of an encrypted plaintext equals to zero.
=> bgn issue when plaintext equals to zero fixed

CMakeLists.txt, relic-config.cmake
This allows other CMake projects to automatically include Relic using `FIND_PATH(relic)`.
=> Add relic-config.cmake

include/relic_bn.h, include/relic_dv.h, include/relic_fb.h, include/relic_fp.h, include/relic_pool.h, include/relic_types.h, src/low/avr-asm-158/relic_fp_mul_low.c, src/low/avr-asm-158/relic_fp_sqr_low.c, src/low/curve2251-sse/relic_fb_mul_low_sf.c, src/low/easy/relic_fb_inv_low.c, src/low/easy/relic_fb_itr_low.c, src/low/easy/relic_fb_mul_low.c, src/low/easy/relic_fb_slv_low.c, src/low/easy/relic_fb_sqr_low.c, src/low/easy/relic_fb_srt_low.c, src/low/easy/relic_fp_mul_low.c, src/low/easy/relic_fp_rdc_low.c, src/low/easy/relic_fp_sqr_low.c, src/low/easy/relic_fpx_mul_low.c, src/low/easy/relic_fpx_sqr_low.c, src/low/gmp/relic_fp_mul_low.c, src/low/gmp/relic_fp_sqr_low.c, src/low/msp-asm/relic_fb_mul_low.c, src/low/x64-asm-254/relic_fp_sqr_low.c, src/low/x64-asm-382/relic_fp_rdc_low.c, src/low/x64-asm-455/relic_fp_inv_low.c, src/low/x64-asm-455/relic_fp_rdc_low.c, src/low/x64-asm-638/relic_fp_inv_low.c, src/low/x64-asm-638/relic_fp_rdc_low.c
When used with the RIOT OS project there is a naming clash
for the align define. Ideally each project would prefix their
symbols.
Tested that it builds with all tests.
=> Rename align define to relic_align to avoid conflicts

README.md
Modified link in README "Bulding" to "Building
=> Minor typo in README which prevented access to building documentation

include/relic_arch.h
GCC's -Wsizeof-pointer-memaccess (activated by -Wall) checks calls of the form
strncpy(dest, src, sizeof(X))
And emits a warning if X does not seem to make sense. In Relic, src = X= a constant
string and this triggers gcc's warning.
I replaced stncpy by memcpy. Because the strings being usd do not contain embedded
zeroes, this should not be a proble,
=> Fix GCC warning regarding strcpy.

src/epx/relic_ep2_util.c
Without this, the flag is uninitialized. "Luckily", the uninitialized value evaluates to "true" in most cases, so this was probably never noticed.
=> Correctly intialize the norm flag in ep2_set_infty

src/epx/relic_ep2_util.c
While syncing relic and https://github.com/Chia-Network/bls-signatures I noticed that I made a quite stupid mistake "backporting" this change to relic...this is my second try :see_no_evil:
=> Second try to correctly initialize p->norm

src/bn/relic_bn_div.c
where a = -4, b = 2 gives c = 2 instead of c= 0
Simpler test case
bn_mod_basic(c,a,b) a=-1, b= 1, gives c=1 instead of c=0
int64_t one = 1;
bn_set_dig(a, one);
bn_set_dig(b, one);
bn_neg(a, a);
printf("a = ");
bn_print(a);
printf("b = ");
bn_print(b);
bn_mod_basic(c, a, b);
printf("a mod b = ");
bn_print(c);
=> Add check for zero for remainder to fix issue with bn_mod_basic(c,a,b)

src/low/curve2251-sse/CMakeLists.txt
Hello,
This PR fixes a build issue I was having on macos when compiling with curve2251-sse. Specifically with the follow cmake command:
```
cmake -DALIGN=16 -DARCH=X64 -DARITH=curve2251-sse -DCHECK=off -DFB_POLYN=251 -DFB_METHD="INTEG;INTEG;QUICK;QUICK;QUICK;QUICK;LOWER;SLIDE;QUICK" -DFB_PRECO=on -DFB_SQRTF=off -DEB_METHD="PROJC;LODAH;COMBD;INTER" -DEC_METHD="CHAR2" -DCOMP="-O3 -funroll-loops -fomit-frame-pointer -march=native -msse4.2 -mpclmul" -DTIMER=CYCLE -DWITH="MD;DV;BN;FB;EB;EC" -DWSIZE=64 .
```
Thanks!
=> fix build on macos when compiling with curve2251-sse

src/low/curve2251-sse/CMakeLists.txt
In curve2251-sse the CMAKE_SOURCE_DIR is changed to RELIC_SOURCE_DIR to make it possible to include the project as subproject.
#114 is fixed by this.
=> Change CMAKE_SOURCE_DIR to RELIC_SOURCE_DIR

src/bn/relic_bn_prime.c, test/test_bn.c
While creating a small Python wrapper I encountered some funky problems with the primality tests.
I added a test-suite to explicitly test a small number of prime and non-primes (they failed ;)). And corrected the Miller-Rabin implementation to be consistent with Algorithm 4.24 in the Handbook of Applied Cryptography.
=> Fixing primality testing

include/relic_pc.h
It seems intended behavior for RLC_G1/G2_TABLE to point to RLC_EP/EP2_TABLE
instead of _TABLE_MAX
=> Fix G1/G2 aliases for table size

CMakeLists.txt
Please considering adding this. 
MSVC has two types of runtime libraries. One statically links while the other is a DLL/shared library. To build the Relic with the statically linked runtime library you must use /MT (release builds) or /MTd (debug) while the DLL uses the /MD, /MDd switches.
The default behavior is unchanged (/MD,/MDd) and this option only appears when cmake is targeting MSVC.
Thanks,
Peter
=> added the ability to set the MSVC runtime library

src/fp/relic_fp_param.c
This PR fixes two issues:
- the comment for SECG_160 listed the wrong prime
- the code for computing the KSS-508 prime appears to be incorrect. In particular, it uselessly negates `t1` when it should have negated `t0`. I've checked the expressions in Sage.
=> correct a couple errors in fp_param

CMakeLists.txt, include/relic_core.h, src/ep/relic_ep_curve.c, src/ep/relic_ep_map.c, src/md/relic_md_xof.c, test/test_fp.c
This PR simplifies the hash-to-field code to take advantage of the improved fp_prime_conv function.
Also:
- fix one more instance of md_xmd -> md_xof rename that slipped through
- tiny tweak in test_fp (replace a for loop with a `memmove`)
- fix signed-unsigned comparison in md_xof
- adds a new build flag `AUSAN` that enables ASan and UBSan.
ASan appears to turn up some (real) stack buffer overflows. At a glance, they look like one-byte writes past the end of buffers (so: almost certainly not a security issue, and possibly not even a correctness issue, but definitely worth fixing).
UBSan mostly reports errors caused by left shifts by 64 bits for 64-bit types. These are indeed undefined behavior, but I'm not sure how to avoid them when building a 64-bit mask using a macro like
#define …
=> simplified hash-to-field, other small fixes

src/ep/relic_ep_curve.c, src/ep/relic_ep_map.c, src/epx/relic_ep2_curve.c, src/epx/relic_ep2_map.c, src/tmpl/relic_tmpl_map.h
This PR does two things:
1. Updates the notion of 'sign' to match the latest hash-to-curve draft.
2. Normalizes the output of the isogeny map when `EP_ADD != PROJC`.
=> update notion of 'sign' for mapping ; correctness for affine coords

src/bn/relic_bn_cmp.c
The comparison function was returning incorrect results in the case it receive in argument +0 and -0. A check is added in bn_cmp to handle this case.
Code to test the problem.
```c
#include <stdlib.h>
#include <stdio.h>
#include "relic.h"
int main(int argc, char *argv[]) {
bn_t a, b, c, d;
int res;
core_init();
bn_null(a);
bn_null(b);
bn_null(c);
bn_null(d);
bn_new(a);
bn_new(b);
bn_new(c);
bn_new(d);
bn_rand(a, RLC_POS, RLC_BN_BITS);
bn_copy(b, a);
bn_neg(a, a);
// c and d are now both 0 but of opposite sign due to the implementation of bn_add.
bn_add(c, a, b);
bn_add(d, b, a);
if (bn_cmp(c, d) == RLC_EQ) {
// success!
printf("Success!\n");
res = 0;
}
else {
printf("Failure!\n");
res = 1;
}
bn_free(a);
bn_free(b);
bn_free(c);
bn_free(d);
return res;
}
```
=> Add check in bn_cmp to handle the case of negative 0.

test/test_pc.c
After testing further I noticed that `g1_cmp()` can also produce incorrect values when comparing non-normalized points. Maybe it is related to the [`is_valid` issue](https://github.com/relic-toolkit/relic/issues/147).
=> Add a cmp test in G1 for non-normalized points.

include/relic_ep.h, include/relic_epx.h, include/relic_label.h, src/ep/relic_ep_map.c, src/epx/relic_ep2_map.c, test/test_ep.c, test/test_epx.c
This PR exposes ep_map_dst and ep2_map_dst, which are hash-to-curve functions that take explicit domain separation tags. Applications that use hash-to-curve are expected to set their own DSTs, so exposing these functions will make it possible for implementors to use RELIC for such applications.
#137 adds this function for Edwards curves.
This PR also adds rudimentary tests to make sure that ep_map and ep_map_dst (resp ep2) agree when the DST is set to "RELIC".
=> add mapping functions that take explicit DSTs to ep and epx

include/relic_core.h, src/ep/relic_ep_pck.c, src/relic_core.c, src/relic_util.c
This PR adds:
1) core_set_thread_initializer() which allows an application to do custom per thread initialization (needed for BLS) 
2) IETF BLS serialization
3) #ifndef QUIET util_print() to help compilers that do not support variadic functions
Caution: We modified the ep_pck() and ep_upk() routines to conform to the BLS IETF specification. This change does alter the behavior of Relic!!! See below:
Each x coordinate has two potential y coordinates based on the formula y^2 = x^3 + 4, but in the serialization we only store the x, which can be used to compute the y (sqrt(x^3 + 4))
However, sqrt returns two possibilities, y and -y, since everything is module a prime q, -y = (q - y). So we need to add one bit to the serialization to say which y it is. 
In current Relic, the bit is set to 1 if …
=> core_set_thread_initializer and IETF BLS serialization

src/fp/relic_fp_prime.c, test/test_fp.c
This PR optimizes some computation steps when Montgomery reduction is used.
It makes the following changes:
- `fp_prime_conv`: converting to `fp` uses an `fp`-multiplication by `R^2 mod p` instead of the shift and reduction.
-  adding a test to check the consistency of `fp_prime_conv` and `fp_prime_back`.
- `fp_prime_init` : computing `R^2 mod p` is done more efficiently by converting the constant 2 to `fp` and using an `fp`-exponentiation by the bit-size of `R`.
=> Optimize some Montgomery reduction steps

src/bn/relic_bn_mxp.c
I assume this printf was left by accident and it is ok to remove it.
=> Remove debug printf in bn_mxp_slide

include/relic_alloc.h, src/rand/relic_rand_core.c
I didn't test a521e8b but i assume its also required since 8c1c1fd is required because there is no `alloca.h` in win/mingw.
Also it doesn't seem to like includes starting with upper-case, hence 11b1f42.
=> Fix MinGW build

src/pc/relic_pc_util.c
The `pc_core_calc` has already calculated the generator for Gt. There is no need to calculate it anymore.
=> Simplify generator getting for Gt.

include/relic_ep.h, include/relic_epx.h, src/ep/relic_ep_map.c, src/epx/relic_ep2_map.c
The set of admissible hash-to-field functions in the [draft hash-to-curve RFC](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-11) now far exceeds what's available md_xmd,
may exceed what is reasonable for Relic to implement, and will not include the customization described in [5.4.4](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve-11#section-5.4.4).
As a consequence, this adds an API for accessing the map-to-curve mapping from pre-hashed bytes of the correct size.
=> Add a direct field-to-curve map

include/relic_fpx.h
`fp48_conv_cyc()` and `fp54_conv_cyc()` are both declared twice, leading to trivial compiler warnings in downstream projects.
=> Remove redundant declarations in relic_fpx.h

bench/bench_pc.c, src/cp/relic_cp_phpe.c
With the generator g=1+n, some exponentiations are not needed.
Saves 2 in phpe key generation: this is all of the exponentiations in cp_phpe_gen
Saves 1 in phpe encryption: this is one out of two in p_phpe_enc
=> Less exponentiations in phpe

src/relic_util.c
Optimize the permutation function by merging the array initialization step into the permutation.
([inside-out version](https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle#The_%22inside-out%22_algorithm) of Fisher-Yates)
(please feel free to make any updates to the PR before merging)
=> Minor permutation optimization

include/relic_ep.h, include/relic_fp.h, src/ep/relic_ep_param.c, src/fp/relic_fp_param.c, src/pp/relic_pp_exp_k12.c
1. RELIC has already supported the SM9 standard (the Chinese national cryptography standard for Identity Based Cryptography), but the pairing result is not consistent with the exmaple given in the SM9 standard. Therefore, I modified the final exponentiation part for SM9 and added `pp_exp_sm9()` to `relic_pp_exp_k12.c`, so that the pairing result is consitent.
2. Add support for SM2 standard (the Chinese national cryptography standard for elliptic curve based cryptography).
=> Add support for Chinese national cryptography standard

.github/workflows/cifuzz.yml
Add [CIFuzz](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) workflow action to have fuzzers build and run on each PR.
This is a service offered by OSS-Fuzz where RELIC already runs. CIFuzz can help detect catch regressions and fuzzing build issues early, and has a variety of features (see the URL above). In the current PR the fuzzers gets build on a pull request and will run for 300 seconds.
Signed-off-by: David Korczynski <david@adalogics.com>
=> Add CIFuzz Github action.

src/bn/relic_bn_prime.c
This improves bn_gen_prime_factor, generating a prime with large (p-1) prime factor.
Once the large prime factor, a, is found, 
- the previous version:
- tries to find primes p of the form 1 + a * (t+u) with random t and increasing u from 0
- until p is prime and of the desired size
- the new version:
- fixes t to be a power of two, and makes random selections of u's, so that p is almost always of the desired size
- until p is prime and of the desired size
- the new version can be an order of magnitude faster on average, but also for the worst cases.
=> Instead of hoping for the correct number of bits, fix the largest bit

demo/link-test/Makefile, include/relic_label.h
When linking multiple Relic Builds with MULTI Macro for both libraries, building will result in the following error: 
```
/usr/bin/ld: /usr/local/lib/librelic_s_type3.a(relic_core.c.o):(.bss+0x8): multiple definition of `core_thread_initializer'; /usr/local/lib/librelic_s_type1.a(relic_core.c.o):(.bss+0x8): first defined here
/usr/bin/ld: /usr/local/lib/librelic_s_type3.a(relic_core.c.o):(.bss+0x0): multiple definition of `core_init_ptr'; /usr/local/lib/librelic_s_type1.a(relic_core.c.o):(.bss+0x0): first defined here
```
I have modified the `link-test` demo to reproduce this error, and created macros for the affected symbols.
=> Fix Linking of multiple builds with MULTI on

include/relic_util.h
Fix: 1 typo in comment section of relic_util.h.  `endianess`  ->  `endianness`
=> Fix 1 typo in comment section of relic_util.h

.gitignore
This PR adds all executables and temporary files used by test programs from `demo` directory to the `.gitignore` file.
Without this PR after compilation of test programs from `demo` directory git starts to track some unnecessary files:
```
$ git status
On branch main
Your branch is up to date with 'origin/main'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
demo/cert-input/test-bench
demo/general-paillier/test
demo/public-stats/data.csv
demo/public-stats/data_04_13.csv
demo/public-stats/main
demo/tweedledum/main
nothing added to commit but untracked files present (use "git add" to track)
```
with this PR these files are not tracked by git:
```
$ git status
On branch gitignore-demo-executables
Your branch is up to date with …
```
=> gitignore: add demo executables
